# Generated by Django 5.0.6 on 2024-07-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_grocery', '0002_product_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product_grocery/static/images/'),
        ),
    ]
