# Generated by Django 5.0.6 on 2024-07-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
