# Generated by Django 5.0.6 on 2024-07-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_cartitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='category',
        ),
    ]
