# Generated by Django 5.0.6 on 2024-07-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_rename_cart_product_collection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_collection',
        ),
    ]
