# Generated by Django 5.0.6 on 2024-07-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_album_alter_feedback_created_at_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
