# Generated by Django 5.0.6 on 2024-07-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
