# Generated by Django 5.0.6 on 2024-07-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
