# Generated by Django 5.0.6 on 2024-07-04 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_collectioncart_created'),
        ('product_grocery', '0005_alter_product_category_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncart',
            name='product',
            field=models.ForeignKey(blank=True, default={'objects': []}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_grocery.product'),
        ),
    ]
